import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LoginOutBtn from "./LoginOutBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  console.log(session);
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/" className="logo">
            EmonForum
          </Link>
          <Link href="/list">List</Link>
          {
            // 조건식 ? 조건식참일때실행할코드 : 거짓일대실행할코드
            session ? (
              <span>
                {session.user.name} <LoginOutBtn />
              </span>
            ) : (
              <LoginBtn />
            )
          }
        </div>
        {children}
      </body>
    </html>
  );
}
